### ISSUE TITLE
How to disable Wazuh Opensearch Dashboard login screen

### ISSUE THREAD

**Issue by ramzcode** [wazuh/wazuh-dashboard#123]
Hi Team,

I am trying to disable the dashboard login screen for some reasons, but i could not find any document or steps to do that. 

If someone can explain it would be great.

thanks in advance

**Comment by AlexRuiz7** [comment]
Hello @ramzcode 

You can do that it two ways:

- [Disabling security](https://opensearch.org/docs/latest/security/configuration/disable/).
- Enabling anonymous access: this option uses the security features and an anonymous user with limited permissions. Check how it works in https://playground.opensearch.org

To enable anonymous access, follow this guide:

---------------------------------

# Setup OpenSearch/Wazuh Dasboard with anonymous access enabled

## Indexer

1. Set `anonymous_auth_enabled: true` in `config.yml` to enable anonymous access to the cluster.

- OpenSearch: `/usr/share/opensearch/config/opensearch-security/config.yml`
- Wazuh: `/etc/wazuh-indexer/opensearch-security/config.yml`

2. Create a new role with the required permissions:

- OpenSearch: `/usr/share/opensearch/config/opensearch-security/roles.yml`
- Wazuh: `/etc/wazuh-indexer/opensearch-security/roles.yml`

```yml
opendistro_security_anonymous:
  reserved: true
  cluster_permissions:
    - 'cluster_composite_ops_ro'
  index_permissions:
    - index_patterns:
        - '*'
      allowed_actions:
        - 'read'
        - 'search'
        - 'indices:admin/mappings/fields/get*'
        - 'indices:data/read/search'
```

3. Create a new role mapping for the anonymous user:

- OpenSearch: `/usr/share/opensearch/config/opensearch-security/roles_mapping.yml`
- Wazuh: `/etc/wazuh-indexer/opensearch-security/roles_mapping.yml`

```yml
opendistro_security_anonymous:
  backend_roles:
  - "opendistro_security_anonymous_backendrole"
```

4. Apply changes using the `securityadmin.sh` script.

- OpenSearch:
```shell
cd /usr/share/opensearch/plugins/opensearch-security/tools/
./securityadmin.sh -cd ../../../config/opensearch-security/ -icl -nhnv -cacert ../../../config/root-ca.pem -cert ../../../config/kirk.pem -key ../../../config/kirk-key.pem
```

- Wazuh Indexer:
**ONLY FOR THE CHANGED FILES**
Otherwise, it will overwrite the entire configuration and break the cluster.
```shell
# Update the configuration for config.yml
OPENSEARCH_CONF_DIR="/etc/wazuh-indexer" JAVA_HOME="/usr/share/wazuh-indexer/jdk" runuser wazuh-indexer -s "/bin/bash" -c "/usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh -f /etc/wazuh-indexer/opensearch-security/cocnfig.yml -icl -nhnv -cacert /etc/wazuh-indexer/certs/root-ca.pem -cert /etc/wazuh-indexer/certs/admin.pem -key /etc/wazuh-indexer/certs/admin-key.pem -t config"

# Update the configuration for roles.yml
OPENSEARCH_CONF_DIR="/etc/wazuh-indexer" JAVA_HOME="/usr/share/wazuh-indexer/jdk" runuser wazuh-indexer -s "/bin/bash" -c "/usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh -f /etc/wazuh-indexer/opensearch-security/roles.yml -icl -nhnv -cacert /etc/wazuh-indexer/certs/root-ca.pem -cert /etc/wazuh-indexer/certs/admin.pem -key /etc/wazuh-indexer/certs/admin-key.pem -t roles"

# Update the configuration for roles_mapping.yml
OPENSEARCH_CONF_DIR="/etc/wazuh-indexer" JAVA_HOME="/usr/share/wazuh-indexer/jdk" runuser wazuh-indexer -s "/bin/bash" -c "/usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh -f /etc/wazuh-indexer/opensearch-security/roles_mapping.yml -icl -nhnv -cacert /etc/wazuh-indexer/certs/root-ca.pem -cert /etc/wazuh-indexer/certs/admin.pem -key /etc/wazuh-indexer/certs/admin-key.pem -t rolesmapping"
```

## Dashboards

1. Set `opensearch_security.auth.anonymous_auth_enabled: true` in `config/opensearch_dashboards.yml` to enable anonymous access to the cluster.

- OpenSearch: `/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml`
- Wazuh: `/etc/wazuh-dashboard/opensearch_dashboards.yml`


2. Restart service.

```shell
systemctl restart wazuh-dashboard
```

3. Access to the UI using one of the following URLs:

- `https://<your_ip>:5601`
- `https://<your_ip>:5601/auth/anonymous`

To login as usual, use this URL:

- `https://<your_ip>:5601/app/login`

**Comment by AlexRuiz7** [comment]
@ramzcode perfect. Can I close this issue then?

**Comment by ramzcode** [comment]
@AlexRuiz7 Sure Please , and thank you for your support.
