### ISSUE TITLE
Fix home logo link

### ISSUE THREAD

**Issue by jbiset** [wazuh/wazuh-dashboard#228]
## Resume

The link configured in the home logo in the top bar has a repeat `app`. On internal browser tab routing, this doesn't seem to affect. However, if a new tab is opened from that link the application does not load correctly, displaying the "`Application Not Found`" screen because it is an invalid URL.
This link needs to be corrected so that the case described above does not occur.

### To Reproduce
1. Go to Overview screen
2. Open a new tab or window from the home logo link
3. The "`Application Not Found`" screen is displayed

### Expected behavior
The screen assigned to the home must be loaded correctly

### Screenshots

**Screen showing the current link that has the home logo**

![image](https://github.com/wazuh/wazuh-dashboard/assets/43619595/63353c8e-3692-47c9-a4e5-19c027fa2b86)

**"`Application Not Found`" screen currently loading with the issue**

![image](https://github.com/wazuh/wazuh-dashboard/assets/43619595/7567b1b2-f8ff-47a5-b886-584d4c6345cf)

**Code associated to the Issue**

![image](https://github.com/wazuh/wazuh-dashboard/assets/43619595/e1a832a7-e38a-48e2-8400-7fd19878baf3)

**Comment by lucianogorza** [comment]
We found that the error occurs with OpenSearch 2.14 and Wazuh 4.10.0, so we have updated the affected release.

**Comment by yenienserrano** [comment]
This issue affects when opensearch version is 2.14.0 or higher because of the change in the redirect method.

2.13.0 > 

`homeHref={http.basePath.prepend('/app/home')}`

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2.13.0/src/core/public/chrome/chrome_service.tsx#L255

2.14.0 <

`homeHref={application.getUrlForApp('home')}`

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2.14.0/src/core/public/chrome/chrome_service.tsx#L272
