### ISSUE TITLE
wazuh agent

### ISSUE THREAD

**Issue by Malwazu** [wazuh/wazuh-dashboard#434]
how admin knows  which wazuh agent uninstalled  by user??

**Comment by yenienserrano** [comment]
HI @Malwazu from what I understand you want to know how does the manager to know if the agent is unistalled on the machine.

I've been testing and when an agent is uninstalled it appears as disconnected agent.

If you know that the agent is disconnected because the agent was unistalled from the machine for a specific reason, you can remove it from the manager so that the agent does not appear as this documentation says.

https://documentation.wazuh.com/current/user-manual/agent/agent-management/remove-agents/index.html
