### ISSUE TITLE
Shown Wazuh API version is wrong or empty after upgrade

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-dashboard#440]
**Describe the bug**

During https://github.com/wazuh/wazuh/issues/27183, it was found that Wazuh API version shown is not the current one after upgrading from v4.9.2 to v4.10.0-rc1

![image](https://github.com/user-attachments/assets/22f31553-ed97-4a19-b81d-6962a5fa00bc)

After cleaning the cache, the error is worse

![image](https://github.com/user-attachments/assets/217a5f75-54cd-4868-a69a-1b0ec24dea86)

**To Reproduce**

See https://github.com/wazuh/wazuh/issues/27183

**Expected behavior**

Wazuh API is v4.10.0

![image](https://github.com/user-attachments/assets/54d2ba0e-2c8d-4dfe-a3d3-10c065a13a18)

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by Tostti** [comment]
The problem was reproducible. 

![before](https://github.com/user-attachments/assets/633ad8bc-05bd-47d8-88fc-c71e95e3e890)
![after](https://github.com/user-attachments/assets/04cbbe3d-c974-467e-b398-12e872012f40)

**Comment by guidomodarelli** [comment]
I have been reviewing where the data in the `Version` column of the table comes from, and I found that the information originates from a request made to the server (GET `/manager/version/check?force_query=${forceQuery}`), which in turn makes a request to the CTI. In this case, since `v4.10.0-rc1` is not yet in production, CTI is unaware of the existence of this version and does not return the expected information, including the current API details. To address this issue, considering that a failure in the request to CTI occurs, I plan to resolve this directly by making a direct request to the server at `/` to inquire about the version.

**Comment by marekzima** [comment]
I've got the same error even when using production WAZUH 4.10.1-1 release!
