### ISSUE TITLE
Include node options in node exec

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard#468]
# Description

We need to include NodeJS options in the node exec command so the fallback can read them.

Reference:

https://github.com/wazuh/wazuh-dashboard/blob/master/scripts/use_node#L100-L102

**Comment by Tostti** [comment]
The Node binary to use (main or fallback) is configured to the variable `$NODE`

https://github.com/wazuh/wazuh-dashboard/blob/4be8d9c4778c87b4024d7aa66b7a2a5efb07d025/scripts/use_node#L50-L72

The NodeJS options (that may be configured in the `node.options` file), are already being set in an environment variable `OSD_NODE_OPTS`

https://github.com/wazuh/wazuh-dashboard/blob/4be8d9c4778c87b4024d7aa66b7a2a5efb07d025/scripts/use_node#L94-L96

Which is then read, and together with other fields are set to `NODE_OPTIONS` before the execution of Node

https://github.com/wazuh/wazuh-dashboard/blob/4be8d9c4778c87b4024d7aa66b7a2a5efb07d025/scripts/use_node#L99-L103

This should be enough to enable the options, as the `NODE_OPTIONS` variable is supported since node v8.0 (https://nodejs.org/dist/v8.17.0/docs/api/cli.html#cli_node_options_options)
