### ISSUE TITLE
Change compressing format for `tar` archives

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-dashboard#85]
## Description

We have detected differences in size between RPM and DEB packages. The packages generated by the tools implemented in 

- #58  

are larger than those generated before the fork.

A brief investigation showed up that the tar files use different formats. Pre-fork tools use `tar.xz` format to generate tarball, while fork tools use `tar.gz` format. This increase in size is propagated to the RPM and DEB packages, which use the tarball as part of the bundle.

**Comment by Tostti** [comment]
Changed the format used in the base and the RPM generator. Can confirm that the difference in size beteween the packages generated with `tar.gz` and `tar.xz` files is minimal.

![image](https://github.com/wazuh/wazuh-dashboard/assets/42900763/9c1f6d5a-3c76-4a63-ada3-69b4e5cb07ec)

We observeda big difference in size of the pre-fork tools generated packages and the fork tools generated packages, but the cause is not the compress format. Further investigation is needed.

**Comment by Tostti** [comment]
Comparing the size of a package made with the pre-fork tools and the post-fork tools, the difference is a lot bigger
![image](https://github.com/wazuh/wazuh-dashboard/assets/42900763/cc35bdea-41dd-402f-b3c6-a87eb98c086e)

Analyzed the package with the `pkgdiff` tool, getting [this output](https://drive.google.com/file/d/1aeGUBxepCGkqTu2vMBOD9Tvn2lKNBdzD/view?usp=sharing) (is an HTML file that can be opened in any browser). The first package is the pre-fork and the second is the post-fork. 

The next step will be inspecting that file to seek the origin of the size difference.

**Comment by AlexRuiz7** [comment]
Which command did you use compress in `xz` format?

**Comment by Tostti** [comment]
@AlexRuiz7 I used `tar -cJf` for that. The difference in size is visible between `.tar.gz` and `.tar.xz` base files.
![image](https://github.com/wazuh/wazuh-dashboard/assets/42900763/b7178d06-1818-411e-9c56-395f43200b46)

**Comment by AlexRuiz7** [comment]
LGTM!
